#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

define('BASE_PATH', __DIR__);

use Symfony\Component\Console\Application;

$console = new Application();

$dotenv = new Dotenv\Dotenv(BASE_PATH);
$dotenv->load();

$console->add(new App\Command\ReplCommand());

$console->run(new Symfony\Component\Console\Input\StringInput('cryptic'));